# 线上配置文件
# @author hwang
# 
server:
  port: 8121
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.120.42.45:3306/huangOj_system
    username: root
    password: xiaoHuang@3846
  # Redis 配置
  # todo 需替换配置
  redis:
    database: 2
    host: 47.120.42.45
    port: 6379
    timeout: 5000
    password: xiaoHuang@3846
  # Elasticsearch 配置
  # todo 需替换配置
#  elasticsearch:
#    uris: http://47.120.42.45:9200
#    username: root
#    password: xiaoHuang@3846
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 接口文档配置
knife4j:
  basic:
    enable: true
    username: root
    password: xiaoHuang@3846
